### ISSUE TITLE
建议添加语言手动切换

### ISSUE THREAD

**Issue by stevened7246** [daidr/paimon-webext#13]
如题

**Comment by daidr** [comment]
是希望切换为什么语言呢？
浏览器拓展的语言和浏览器语言保持一致，似乎是不能单独修改的（浏览器语言可以通过启动参数 `--lang=xx` 来修改）

**Comment by stevened7246** [comment]
主要是我使用繁体然后预设英文看不惯
[messages.txt](https://github.com/daidr/paimon-webext/files/9213079/messages.txt)
翻译繁体完了，但是不保证翻译准确性🤣（简繁体不分者）

**Comment by daidr** [comment]
感谢，繁体中文支持会在 0.0.7 版本加入，因为会有新功能（树脂提示），或许会需要一些时间。
