### ISSUE TITLE
建议在树脂等快要满的时候，打开浏览器会有提示

### ISSUE THREAD

**Issue by MiSheep** [daidr/paimon-webext#14]
建议树脂，洞天宝钱，探索，参变等快要满的时候给个提示，这个数值可选。比如树脂提示的单选框勾选后，填入文本“155”，那么我打开浏览器时这个插件能帮我查询这些值，如果树脂符合条件，那么给我个提示。

**Comment by daidr** [comment]
已经在做了，可能用浏览器的通知和popup角标

**Comment by daidr** [comment]
在 0.0.8 版本中，此功能已经实现
