### ISSUE TITLE
设置界面UI稍微有点小问题

### ISSUE THREAD

**Issue by SummerFlyer** [daidr/paimon-webext#16]
关于页面右侧一部分为白色
![image](https://user-images.githubusercontent.com/66506891/184653732-76d043e7-0fdf-406c-9ee0-3af2f468d45e.png)
建议将左侧图形缩小
![image](https://user-images.githubusercontent.com/66506891/184654123-aecc6e83-72ac-4871-a890-e121bab3633d.png)
居中应该会更加美观

**Comment by daidr** [comment]
确实有这个问题，会在下个版本修复
