### ISSUE TITLE
似乎数据停止更新了

### ISSUE THREAD

**Issue by dspjm** [daidr/paimon-webext#23]
世界树服务器。数据跟实际上不符。卸载重装后依然如此。

**Comment by daidr** [comment]
能具体描述一下是哪些地方不符么

**Comment by dspjm** [comment]
![image](https://user-images.githubusercontent.com/3742673/192953268-bede7757-da7c-4016-9573-44fc1b2f14ed.png)

数据停留在这个状态已经好多天了。我用的是火狐。卸载插件后数据不知道是不是重新获取了，但是依然是这样的。

**Comment by daidr** [comment]
鼠标移动到Current Resin旁边，可以看到最近一次更新的时间（正常应该在一分钟以内）
倘若发现数据不同步，可以尝试登录米游社后重复一遍角色添加流程

没有b服账号，还在过新手教程，这两天可能复现不了😂

**Comment by dspjm** [comment]
似乎是火狐独有的问题。我在edge上同一个账号是好用的。

**Comment by daidr** [comment]
了解了，等我过完b服的剧情会尝试在firefox中复现一下。

**Comment by dspjm** [comment]
现在恢复正常了
