### ISSUE TITLE
请更新，增加日语的内容。

### ISSUE THREAD

**Issue by Rigaln** [daidr/paimon-webext#25]
请更新，增加日语的内容。

**Comment by daidr** [comment]
哇，感谢提供日语翻译，日语本地化支持会在0.0.9版本加入👍

**Comment by Rigaln** [comment]
下一次更新计划是什么时候？

**Comment by daidr** [comment]
大概在10月5日之前

**Comment by Rigaln** [comment]
谢谢你。
要求。
我希望你能添加一个24小时的计时器，只需点击一下就能工作。
所以我可以收集遗物，然后24小时后我可以再次收集它。

**Comment by daidr** [comment]
了解了，手动计时器会在0.0.10版本增加，在此之前可以先使用系统自带的计时器软件代替
