### ISSUE TITLE
接口可能返回1034错误

### ISSUE THREAD

**Issue by daidr** [daidr/paimon-webext#29]
接口触发风控可能返回1034错误，此时需要请求验证码

附加（WIP）:
国服采用极验验证
相关接口
https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/createVerification?is_high=true 用于获取校验挑战
https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/verifyVerification 用于提交挑战结果，成功后返回retcode: 0及原始挑战字符串

国际服存在相关接口，不过暂时没有触发风控的案例

**Comment by swordmitri** [comment]
遇到这个情况了 而且验证码出现的太频繁了 经常是刚到米游社app验证了之后5分钟就继续触发风控 不知道是否有方法解决

**Comment by daidr** [comment]
> 遇到这个情况了 而且验证码出现的太频繁了 经常是刚到米游社app验证了之后5分钟就继续触发风控 不知道是否有方法解决

我感觉可能是浏览器拓展的某个特征被mhy检测到了，我尝试延长了刷新数据的时间，并且在最新的一次commit中，将验证码做到了拓展中

建了一个Q群方便沟通：757411736

**Comment by ArvinZJC** [comment]
> 接口触发风控可能返回1034错误，此时需要请求验证码
> 
> 附加（WIP）: 国服采用极验验证 相关接口 https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/createVerification?is_high=true 用于获取校验挑战 https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/verifyVerification 用于提交挑战结果，成功后返回retcode: 0及原始挑战字符串
> 
> 国际服存在相关接口，不过暂时没有触发风控的案例

在这两个接口的基础上可以直接做无感验证，可以减少打扰

**Comment by daidr** [comment]
> > 接口触发风控可能返回1034错误，此时需要请求验证码
> > 附加（WIP）: 国服采用极验验证 相关接口 https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/createVerification?is_high=true 用于获取校验挑战 https://api-takumi-record.mihoyo.com/game_record/app/card/wapi/verifyVerification 用于提交挑战结果，成功后返回retcode: 0及原始挑战字符串
> > 国际服存在相关接口，不过暂时没有触发风控的案例
> 
> 在这两个接口的基础上可以直接做无感验证，可以减少打扰

感谢，确实可以在一定程度上减少手动验证的次数
