### ISSUE TITLE
提示发生错误无法使用

### ISSUE THREAD

**Issue by HONOLR** [daidr/paimon-webext#32]
反复添加并删除了账户，但是会一直出现发生错误

**Comment by daidr** [comment]
#29 可以参见这个issue，因为米游社风控的原因

你可以使用 release 里的 0.0.11 版本，解决了风控问题。chrome也可以直接在商店里更新，edge商店还在审核。

后续如果还频繁出现问题，也可以加Q群：757411736，我会尽可能帮你解决
