### ISSUE TITLE
验证频率过高

### ISSUE THREAD

**Issue by XYZ-dragon** [daidr/paimon-webext#37]
如果去模拟正常用户打开APP时的请求动作能否恢复正常?
另外定时刷新数据似乎也是一个问题,这看起来太像机器人了(?

或者自动在后台搞定验证码,看起来难度更高.

**Comment by daidr** [comment]
0.0.12 版本会尝试加入自定义刷新时间间隔的功能，尝试缓解风控的问题。

**Comment by Notofnice** [comment]
> 0.0.12 版本会尝试加入自定义刷新时间间隔的功能，尝试缓解风控的问题。

或许能否加个开关？让用户选择是否开启自动刷新，仅在点击扩展的时候获取并刷新数据

**Comment by dspjm** [comment]
> > 0.0.12 版本会尝试加入自定义刷新时间间隔的功能，尝试缓解风控的问题。
> 
> 或许能否加个开关？让用户选择是否开启自动刷新，仅在点击扩展的时候获取并刷新数据

这个好。最近总是获取失败，有时候有大多数时候没有，是这个原因吗？

**Comment by daidr** [comment]
> 

目前测试下来凌晨的那段时间很容易被风控
