### ISSUE TITLE
仅靠减少请求次数可能无法避免触发人机验证

### ISSUE THREAD

**Issue by baoochn** [daidr/paimon-webext#39]
为了避免请求次数太多，我把这个扩展装到了一个不常用的chrome副本上，每天只点开看3-5次，且不保留后台。
似乎在0:00-9:00这段时间必触发风控，其他时间则基本不会，也有可能是每天的第一次请求会触发。
因此猜测仅靠减少请求次数可能无法避免触发人机验证。

**Comment by baoochn** [comment]
这两天似乎问题更严重了，打开米游社都需要拖动验证码才能看，PC客户端一直掉登录，每次登录都要输密码+拖动验证码

**Comment by daidr** [comment]
我最近也在尝试通过各种方法缓解风控的问题，但是基本上每天就风控3-4次，会不会是其他软件的影响？

**Comment by baoochn** [comment]
> 我最近也在尝试通过各种方法缓解风控的问题，但是基本上每天就风控3-4次，会不会是其他软件的影响？

米游社网页登录加了一个安全检测，之后就无法通过扩展导入cookie了，提示获取角色失败

**Comment by daidr** [comment]
> > 我最近也在尝试通过各种方法缓解风控的问题，但是基本上每天就风控3-4次，会不会是其他软件的影响？
> 
> 
> 
> 米游社网页登录加了一个安全检测，之后就无法通过扩展导入cookie了，提示获取角色失败

我尝试了一下，还是可以的呀？要不你再试试

**Comment by baoochn** [comment]
> > > 我最近也在尝试通过各种方法缓解风控的问题，但是基本上每天就风控3-4次，会不会是其他软件的影响？
> > 
> > 
> > 米游社网页登录加了一个安全检测，之后就无法通过扩展导入cookie了，提示获取角色失败
> 
> 我尝试了一下，还是可以的呀？要不你再试试

您尝试用一个全新的浏览器，或者给现有的浏览器增加一个用户，之后登录米游社并导入扩展，就不行了。
我昨天发现这问题就是想用一个单独的浏览器用户进一步降低请求次数，然后就发现了。

**Comment by baoochn** [comment]
我又试了一下，只要浏览器阻止安全检查的窗口弹出，扩展就可以获取cookie了
