### ISSUE TITLE
米游社APP的内建浏览器UA

### ISSUE THREAD

**Issue by baoochn** [daidr/paimon-webext#41]
安卓客户端，在系统webview的UA后面添加了 miHoYoBBS/2.40.1
也许请求api的时候带上这个可以规避验证

**Comment by daidr** [comment]
在最近尝试过了，之后的版本会加上，但似乎仍然会触发风控。

不出意外，新版本(0.1.0)在经过明后两天的测试之后会发布出来

**Comment by baoochn** [comment]
确实还会触发.......
