### ISSUE TITLE
Firefox最高版本只有0.09

### ISSUE THREAD

**Issue by bailijerry** [daidr/paimon-webext#43]

**Comment by daidr** [comment]
因为chrome和edge现在都开始推行manifest v3扩展，但是firefox的v3支持还停留在不可用的状态，所以暂时没有更新。
预计解决完风控的问题之后就会开始firefox版本的重构了，抱歉

**Comment by Small-Ku** [comment]
https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/

> To be clear, Firefox will continue to support MV2 extensions for the foreseeable future, even as we welcome MV3 extensions in the release to general availability in Firefox 109 (January 17, 2023).

> 讓我們明確一點，Firefox將繼續支援MV2擴展，即使我們在Firefox 109中歡迎MV3擴展（2023年1月17日）也是如此。

現在應該是有 Manifest v3 了？

**Comment by daidr** [comment]
firefox更新了0.1.4版本，可以试一下啦

**Comment by Small-Ku** [comment]
用上了！感謝！
