### ISSUE TITLE
无法登录，总是获取角色失败

### ISSUE THREAD

**Issue by CarterLi** [daidr/paimon-webext#47]
![image](https://user-images.githubusercontent.com/6134068/210384503-63779daa-7ea6-416b-9e0a-b32003fc87a3.png)

和最近米游社换域名有关么？

**Comment by daidr** [comment]
具体我明天排查一下

**Comment by daidr** [comment]
https://github.com/daidr/paimon-webext/releases/tag/0.1.2

已修复，chrome应该可以直接下载crx拖入进行更新

**Comment by CarterLi** [comment]
手工更新了版本，仍然获取角色失败

<img width="741" alt="image" src="https://user-images.githubusercontent.com/6134068/210503132-57a2444d-3e33-4673-a87b-e49670893b8d.png">

**Comment by daidr** [comment]
我没法复现，尝试 https://www.miyoushe.com/ys/ 退出重新登录下，然后再获取角色能够成功么

**Comment by CarterLi** [comment]
origin refer host是不是应该换一下？

这是扩展的请求
![image](https://user-images.githubusercontent.com/6134068/210810994-6ed90582-16c1-48f6-9787-ce14901bc954.png)

这是米游社合法的请求
![image](https://user-images.githubusercontent.com/6134068/210811124-904cffbd-775a-4e2d-a78a-a9f4500396b6.png)

**Comment by CarterLi** [comment]
对

**Comment by ArvinZJC** [comment]
猜测根因：`ltoken_v2` 和 `cookie_token_v2` 值中的 `=` 被编码成了 `%3d`

cookie 中实际生效部分可参见[此 wiki](https://github.com/ArvinZJC/PaimonTray/wiki/Guide-on-how-to-get-your-cookies#cookie-names-that-should-be-contained-in-the-cookies)，背景是实际生效的 cookie 一部分在某些情况下被米设成了 http-only，所以出问题的场景一般是不得不尝试取 v2 token，这种 token 值比 `ltoken` 复杂，可能会含 `=`

**Comment by daidr** [comment]
修复了，可以下载文件直接拖入浏览器扩展页面安装
https://github.com/daidr/paimon-webext/releases/download/0.1.3/paimon_chrome.crx
