### ISSUE TITLE
插件导致 cookie 失效

### ISSUE THREAD

**Issue by XYZ-dragon** [daidr/paimon-webext#53]
刚登录就去插件选项点击获取 cookie, 第一次是显示正常的 (此时已经掉登录了), 刷新或者再点一次就会显示获取失败.
并且掉登录这件事不应该发生才对, 重复试了几次都是这样. 大概是又改了验证罢(悲
并且我目前点击插件图标只会显示一个很小的纯白框
version: 0.1.3

**Comment by daidr** [comment]
是风控导致的，临时的解决方案是进入米游社APP并完成验证码。
尝试在 paimon-webext 中降低刷新频率，能够缓解该情况，目前在寻找解决办法

**Comment by daidr** [comment]
0.1.5版本已修复
