### ISSUE TITLE
突然出现白色小窗口，重新添加角色也没用。不知道如何解决

### ISSUE THREAD

**Issue by 0000000O** [daidr/paimon-webext#54]
![image](https://user-images.githubusercontent.com/86942399/232246650-5f889f6f-93da-49ce-b382-abbaed6ab14e.png)

**Comment by daidr** [comment]
是风控导致的，临时的解决方案是进入米游社APP并完成验证码。
尝试在 paimon-webext 中降低刷新频率，能够缓解该情况，目前在寻找解决办法

**Comment by 0000000O** [comment]
> 是风控导致的，临时的解决方案是进入米游社APP并完成验证码。 尝试在 paimon-webext 中降低刷新频率，能够缓解该情况，目前在寻找解决办法

是这样的，建议大大能在这个白色小窗口上加入一点点文字提示，要不很没头绪。麻烦您
