### ISSUE TITLE
大佬有兴趣搞一个星铁版本吗

### ISSUE THREAD

**Issue by version4** [daidr/paimon-webext#55]
用习惯了大佬的插件，都不想去米游社看

**Comment by daidr** [comment]
可以的，我过几天看看

**Comment by OtakuCat2020** [comment]
也不是催，但是等了2个月了

> 可以的，我过几天看看

**Comment by daidr** [comment]
> 也不是催，但是等了2个月了
> 
> > 可以的，我过几天看看

啊🌿，完全忘了这回事，这就去写😥😥

**Comment by daidr** [comment]
@version4 @OtakuCat2020 
提交了一个月edge还是拒审，可以先用chrome的版本
 https://chromewebstore.google.com/detail/akaohghdgcakognnomndghdbcinjdjhb
