### ISSUE TITLE
最近总是：“发生错误 当前账号触发风控，需要完成人机验证 点击下面的人机验证按钮”

### ISSUE THREAD

**Issue by OtakuCat2020** [daidr/paimon-webext#56]
RT，我记得之前好像解决过一次，现在又来了。朋友这个能解决吗？

**Comment by daidr** [comment]
之前能够自动过风控实际上是依赖了极验验证码的一个漏洞，后来不行了。
可以把刷新间隔调整到60分钟来缓解这种情况。
如果之后有了更好的办法会及时更新的。

**Comment by daidr** [comment]
已解决，可以升级到0.2.0版本试试啦

**Comment by JadeVane** [comment]
怎么升到0.2.0？release只有0.1.5，仓库也是2周前最后一次提交

![图片](https://github.com/daidr/paimon-webext/assets/34258753/72b0c305-343d-448d-a39b-5a3abc9bd7cd)

**Comment by daidr** [comment]
release里没有 0.2.0 是意料外的情况，我一会儿手动加上
firefox的版本暂时停止更新了，会在firefox完全支持manifest v3后继续更新。兼容完全不同的api带来很大的开发负担还挺大的。
之后如果有新的进展会通知你哒

**Comment by daidr** [comment]
> 怎么升到0.2.0？release只有0.1.5，仓库也是2周前最后一次提交
> 
> 
> 
> ![图片](https://github.com/daidr/paimon-webext/assets/34258753/72b0c305-343d-448d-a39b-5a3abc9bd7cd)
> 
> 

release里没有 0.2.0 是意料外的情况，我一会儿手动加上
firefox的版本暂时停止更新了，会在firefox完全支持manifest v3后继续更新。兼容完全不同的api带来很大的开发负担还挺大的。
之后如果有新的进展会通知你哒
