### ISSUE TITLE
能否增加查看每日摩拉和原石

### ISSUE THREAD

**Issue by chtholist** [daidr/paimon-webext#8]
可以增加查看每日获取的原石&摩拉吗？
米游社的朴记中可以查看每月的原石&摩拉，希望小插件里能可以看到每日的获取情况~
目前已知在SG.Genshin中有实现此功能，但有时不准确https://github.com/DGP-Studio/Snap.Genshin

**Comment by daidr** [comment]
这个感觉可以有，我去了解一下👍

**Comment by stevened7246** [comment]
> 这个感觉可以有，我去了解一下👍

目前有计划吗？

**Comment by daidr** [comment]
> > 这个感觉可以有，我去了解一下👍
> 
> 目前有计划吗？

会在0.0.10版本加入，预计在10月下旬完成开发
